# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: my-patched-bazzite
description: Bazzite with a toggleable mac80211 MCS validation patch for Xfinity XB8 compatibility.

base-image: ghcr.io/ublue-os/bazzite
image-version: 43

modules:
  - type: rpm-ostree
    install:
      - kernel-devel
      - gcc
      - make
      - patch
      - curl
      - xz

  - type: script
    scripts:
      - build-mac80211.sh

  - type: rpm-ostree
    remove:
      - kernel-devel
      - gcc
      - make
