
ARG BAZZITE_VERSION=latest
FROM ghcr.io/ublue-os/bazzite:${BAZZITE_VERSION} AS builder

ARG BAZZITE_VERSION
ARG BUILD_TAG

COPY spec_files /tmp/spec_files
COPY signing_key.x509 /tmp/signing_key.x509

RUN --mount=type=secret,id=mok_priv \
    KVER=$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}' | head -n 1) && \
    dnf install -y rpm-build make gcc kernel-devel-$KVER curl xz openssl coreutils && \
    mkdir -p /rpms /rpmbuild && \
    rpmbuild -bb /tmp/spec_files/mcspatched_mac80211/mcspatched_mac80211.spec \
      --define '_topdir /rpmbuild' \
      --define '_rpmdir /rpms' \
      --define 'mok_priv /run/secrets/mok_priv' \
      --define 'mok_x509 /tmp/signing_key.x509' \
      --define "kversion $KVER" && \
    find /rpms -name '*.rpm' -exec mv {} /rpms/mac80211-kmod.rpm \;

FROM scratch
COPY --from=builder /rpms/mac80211-kmod.rpm /rpms/mac80211-kmod.rpm
